name: Docker Image CI

on:
  push:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - run: echo ${GITHUB_TOKEN} | docker login -u ${GITHUB_ACTOR} --password-stdin docker.pkg.github.com
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - run: docker build . --tag docker.pkg.github.com/crac/docker-build/image:$GITHUB_REF_NAME
    - run: docker push docker.pkg.github.com/crac/docker-build/image:$GITHUB_REF_NAME
